services:
    genre_admin:
        class: GenreBundle\Admin\GenreAdmin
        tags:
          - { name: sonata.admin, manager_type: orm, group: "group.genre", label: Жанры }
        arguments:
          - ~
          - GenreBundle\Entity\Genre
          - ~
        calls:
          - [ setTranslationDomain, [GenreBundle] ]