services:
    genre.block.list_genre:
        class: "GenreBundle\\Block\\ListGenreBlockService"
        arguments:
          - genre.block.list_genre
          - '@templating'
          - '@?doctrine'
        tags:
          - { name: sonata.block }