services:
    author_admin:
        class: AuthorBundle\Admin\AuthorAdmin
        tags:
          - { name: sonata.admin, manager_type: orm, group: "group.author", label: Авторы }
        arguments: [ ~, AuthorBundle\Entity\Author, ~]
        public: true