services:
    author_admin:
        class: AuthorBundle\Admin\AuthorAdmin
        tags:
          - { name: sonata.admin, manager_type: orm, group: "group.author", label: "group.author_editor" }
        arguments:
          - ~
          - AuthorBundle\Entity\Author
          - ~
        calls:
          - [ setTranslationDomain, [AuthorBundle] ]