# books ========================================================
book_view:
    path: /book/{id}-{slug}
    defaults:
        _controller: BookBundle:Book:view
    requirements:
        slug: "([a-zA-Z\\-0-9\\_]+)?"
        id: "\\d+"

year_books:
    path: /year/{year}
    defaults:
        _controller: BookBundle:Book:yearList
