# books ========================================================
book_view:
    path: /book/{id}-{slug}
    defaults:
        _controller: BookBundle:Book:view
    requirements:
        slug: "([a-zA-Z\\-0-9\\_]+)?"
        id: "\\d+"

inc_book_download:
    path: /inc_download/book
    defaults:
        _controller: BookBundle:Book:incDownload

year_books:
    path: /year/{year}
    defaults:
        _controller: BookBundle:Book:yearList
