# books ========================================================
article_view:
    path: /kollekcii-knig/{slug}
    defaults:
        _controller: ArticleBundle:Article:view
    requirements:
        slug: "([a-zA-Z\\-0-9\\_]+)?"

article_list:
    path: /kollekcii-knig
    defaults:
        _controller: ArticleBundle:Article:list
