services:
    sonata.admin.media:
        class: MediaBundle\Admin\MediaFileAdmin
        tags:
          - { name: sonata.admin, manager_type: orm, group: "group.media", label: "group.media_file_editor" }
        arguments:
          - ~
          - MediaBundle\Entity\MediaFile
          - ~
        calls:
          - [ setTranslationDomain, [MediaBundle] ]