parameters:
    files_folder: "%media_base_path%/files/"
    image_folder: "%media_base_path%/images/"

knp_gaufrette:
    stream_wrapper: ~
    adapters:
        file:
            local:
                directory: "%files_folder%"
                create: true
        image:
            local:
                directory: "%image_folder%"
                create: true

    filesystems:
        file:
            adapter: file
        image:
            adapter: image