services:
#  category_admin:
#    class: AppBundle\Admin\CategoryAdmin
#    tags:
#      - { name: sonata.admin, manager_type: orm, group: 'group.article', label: 'group.article.category_editor' }
#    arguments:
#      - ~
#      - AppBundle\Entity\Category
#      - ~
#    calls:
#      - [ setTranslationDomain, [AppBundle] ]
#
#  article_admin:
#    class: AppBundle\Admin\ArticleAdmin
#    tags:
#      - { name: sonata.admin, manager_type: orm, group: 'group.article', label: 'group.article.article_editor' }
#    arguments:
#      - ~
#      - AppBundle\Entity\Article
#      - AdminBundle:CRUD
#    calls:
#      - [ setTranslationDomain, [AppBundle] ]
#      - [ setTemplate, ['edit', 'AppBundle:Admin:edit_article.html.twig'] ]
##      - [ addChild, [@category_has_article_admin]]
#
#  article_has_related_articles_admin:
#    class: AppBundle\Admin\ArticleHasRelatedArticlesAdmin
#    tags:
#      - { name: sonata.admin, manager_type: orm, group: 'group.article', label: 'group.article.article_has_related_articles_editor', show_in_dashboard: false }
#    arguments:
#      - ~
#      - AppBundle\Entity\ArticleHasRelatedArticles
#      - ~
#    calls:
#      - [ setTranslationDomain, [AppBundle] ]
#
#  article_has_related_tv_videos_admin:
#    class: AppBundle\Admin\ArticleHasRelatedTvVideosAdmin
#    tags:
#      - { name: sonata.admin, manager_type: orm, group: 'group.article', label: 'group.article.article_has_related_tv_videos_editor', show_in_dashboard: false }
#    arguments:
#      - ~
#      - AppBundle\Entity\ArticleHasRelatedTvVideos
#      - ~
#    calls:
#      - [ setTranslationDomain, [AppBundle] ]
#
#  article_has_categories_admin:
#    class: AppBundle\Admin\ArticleHasCategoriesAdmin
#    tags:
#      - { name: sonata.admin, manager_type: orm, group: 'group.article', label: 'group.article.article_has_categories_editor', show_in_dashboard: false }
#    arguments:
#      - ~
#      - AppBundle\Entity\ArticleHasCategories
#      - ~
#    calls:
#      - [ setTranslationDomain, [AppBundle] ]
#
#  blogger_admin:
#    class: AppBundle\Admin\BloggerAdmin
#    tags:
#      - { name: sonata.admin, manager_type: orm, group: 'group.blog', label: 'group.blog.blogger_editor' }
#    arguments:
#      - ~
#      - AppBundle\Entity\Blogger
#      - ~
#    calls:
#      - [ setTranslationDomain, [AppBundle] ]
#
#  blog_admin:
#    class: AppBundle\Admin\BlogAdmin
#    tags:
#      - { name: sonata.admin, manager_type: orm, group: 'group.blog', label: 'group.blog.blog_editor' }
#    arguments:
#      - ~
#      - AppBundle\Entity\Blog
#      - AdminBundle:CRUD
#    calls:
#      - [ setTranslationDomain, [AppBundle] ]
#
#  event_admin:
#    class: AppBundle\Admin\EventAdmin
#    tags:
#      - { name: sonata.admin, manager_type: orm, group: 'group.event', label: 'group.event.event_editor' }
#    arguments:
#      - ~
#      - AppBundle\Entity\Event
#      - AdminBundle:CRUD
#    calls:
#      - [ setTranslationDomain, [AppBundle] ]
#
#  collection_admin.designer:
#    class: AppBundle\Admin\CollectionDesignerAdmin
#    tags:
#      - { name: sonata.admin, manager_type: orm, group: 'group.collection', label: 'group.collection.designer_editor' }
#    arguments:
#      - ~
#      - AppBundle\Entity\CollectionDesigner
#      - ~
#    calls:
#      - [ setTranslationDomain, [AppBundle] ]
#
#  collection_admin.season:
#    class: AppBundle\Admin\CollectionSeasonAdmin
#    tags:
#      - { name: sonata.admin, manager_type: orm, group: 'group.collection', label: 'group.collection.season_editor' }
#    arguments:
#      - ~
#      - AppBundle\Entity\CollectionSeason
#      - ~
#    calls:
#      - [ setTranslationDomain, [AppBundle] ]
#
#  collection_admin.type:
#    class: AppBundle\Admin\CollectionTypeAdmin
#    tags:
#      - { name: sonata.admin, manager_type: orm, group: 'group.collection', label: 'group.collection.type_editor' }
#    arguments:
#      - ~
#      - AppBundle\Entity\CollectionType
#      - ~
#    calls:
#      - [ setTranslationDomain, [AppBundle] ]
#
#  collection_admin.category:
#    class: AppBundle\Admin\CollectionCategoryAdmin
#    tags:
#      - { name: sonata.admin, manager_type: orm, group: 'group.collection', label: 'group.collection.category_editor' }
#    arguments:
#      - ~
#      - AppBundle\Entity\CollectionCategory
#      - ~
#    calls:
#      - [ setTranslationDomain, [AppBundle] ]
#
#  collection_admin.fashionweek:
#      class: AppBundle\Admin\CollectionFashionWeekAdmin
#      tags:
#        - { name: sonata.admin, manager_type: orm, group: 'group.collection', label: 'group.collection.fashionweek_editor' }
#      arguments:
#        - ~
#        - AppBundle\Entity\CollectionFashionWeek
#        - ~
#      calls:
#        - [ setTranslationDomain, [AppBundle] ]
#
#  collection_admin:
#      class: AppBundle\Admin\CollectionAdmin
#      tags:
#        - { name: sonata.admin, manager_type: orm, group: 'group.collection', label: 'group.collection.collection_editor' }
#      arguments:
#        - ~
#        - AppBundle\Entity\Collection
#        - AdminBundle:CRUD
#      calls:
#        - [ setTranslationDomain, [AppBundle] ]
#
#  world_vogue:
#    class: AppBundle\Admin\WorldVogueAdmin
#    tags:
#        - { name: sonata.admin, manager_type: orm, group: 'group.world_vogue', label: 'group.world_vogue' }
#    arguments:
#      - ~
#      - AppBundle\Entity\WorldVogue
#      - ~
#    calls:
#      - [ setTranslationDomain, [AppBundle] ]
#
#  gallery_admin:
#    class: AppBundle\Admin\GalleryAdmin
#    tags:
#        - { name: sonata.admin, manager_type: orm, group: 'group.upload', label: 'group.upload.gallery_editor' }
#    arguments:
#      - ~
#      - AppBundle\Entity\Gallery
#      - ~
#    calls:
#      - [ setTranslationDomain, [AppBundle] ]
#
#  gallery_has_image_admin:
#      class: AppBundle\Admin\GalleryHasImageAdmin
#      tags:
#          - { name: sonata.admin, manager_type: orm, group: 'group.upload', label: 'group.upload.gallery_has_image_editor', show_in_dashboard: false }
#      arguments:
#        - ~
#        - AppBundle\Entity\GalleryHasImage
#        - ~
#      calls:
#        - [ setTranslationDomain, [AppBundle] ]
#
#  tv_category_admin:
#    class: AppBundle\Admin\TvCategoryAdmin
#    tags:
#      - { name: sonata.admin, manager_type: orm, group: 'group.tv', label: 'group.tv.tv_category_editor' }
#    arguments:
#      - ~
#      - AppBundle\Entity\TvCategory
#      - ~
#    calls:
#      - [ setTranslationDomain, [AppBundle] ]
#
#  tv_video_admin:
#    class: AppBundle\Admin\TvVideoAdmin
#    tags:
#      - { name: sonata.admin, manager_type: orm, group: 'group.tv', label: 'group.tv.tv_video_editor' }
#    arguments:
#      - ~
#      - AppBundle\Entity\TvVideo
#      - AdminBundle:CRUD
#    calls:
#      - [ setTranslationDomain, [AppBundle] ]
#
#  tv_video_has_related_articles_admin:
#    class: AppBundle\Admin\TvVideoHasRelatedArticlesAdmin
#    tags:
#      - { name: sonata.admin, manager_type: orm, group: 'group.tv', label: 'group.tv.tv_video_has_related_articles_editor', show_in_dashboard: false }
#    arguments:
#      - ~
#      - AppBundle\Entity\TvVideoHasRelatedArticles
#      - ~
#    calls:
#      - [ setTranslationDomain, [AppBundle] ]
#
#  tv_video_has_related_tv_videos_admin:
#    class: AppBundle\Admin\TvVideoHasRelatedTvVideosAdmin
#    tags:
#      - { name: sonata.admin, manager_type: orm, group: 'group.tv', label: 'group.tv.tv_video_has_related_tv_videos_editor', show_in_dashboard: false }
#    arguments:
#      - ~
#      - AppBundle\Entity\TvVideoHasRelatedTvVideos
#      - ~
#    calls:
#      - [ setTranslationDomain, [AppBundle] ]
#
#  magazine_admin:
#    class: AppBundle\Admin\MagazineAdmin
#    tags:
#      - { name: sonata.admin, manager_type: orm, group: 'group.magazine', label: 'group.magazine.magazine_editor' }
#    arguments:
#      - ~
#      - AppBundle\Entity\Magazine
#      - ~
#    calls:
#      - [ setTranslationDomain, [AppBundle] ]
#
#  magazine_has_posts_admin:
#    class: AppBundle\Admin\MagazineHasPostsAdmin
#    tags:
#      - { name: sonata.admin, manager_type: orm, group: 'group.magazine', label: 'group.magazine.magazine_has_posts_editor', show_in_dashboard: false }
#    arguments:
#      - ~
#      - AppBundle\Entity\MagazineHasPosts
#      - ~
#    calls:
#      - [ setTranslationDomain, [AppBundle] ]
#
#  magazine_post_admin:
#    class: AppBundle\Admin\MagazinePostAdmin
#    tags:
#      - { name: sonata.admin, manager_type: orm, group: 'group.magazine', label: 'group.magazine.magazine_post_editor', show_in_dashboard: false }
#    arguments:
#      - ~
#      - AppBundle\Entity\MagazinePost
#      - ~
#    calls:
#      - [ setTranslationDomain, [AppBundle] ]
#
#  horoscope_admin:
#    class: AppBundle\Admin\HoroscopeAdmin
#    tags:
#      - { name: sonata.admin, manager_type: orm, group: 'group.horoscope', label: 'group.horoscope.horoscope_editor' }
#    arguments:
#      - ~
#      - AppBundle\Entity\Horoscope
#      - ~
#    calls:
#      - [ setTranslationDomain, [AppBundle] ]
#
#  informer_admin:
#    class: AppBundle\Admin\InformerAdmin
#    tags:
#      - { name: sonata.admin, manager_type: orm, group: 'group.informer', label: 'group.informer.informer_editor' }
#    arguments:
#      - ~
#      - AppBundle\Entity\Informer
#      - ~
#    calls:
#      - [ setTranslationDomain, [AppBundle] ]
#
#  team_group_admin:
#    class: AppBundle\Admin\TeamGroupAdmin
#    tags:
#      - { name: sonata.admin, manager_type: orm, group: 'group.team', label: 'group.team.group_editor' }
#    arguments:
#      - ~
#      - AppBundle\Entity\TeamGroup
#      - ~
#    calls:
#      - [ setTranslationDomain, [AppBundle] ]
#
#  team_member_admin:
#    class: AppBundle\Admin\TeamMemberAdmin
#    tags:
#      - { name: sonata.admin, manager_type: orm, group: 'group.team', label: 'group.team.member_editor' }
#    arguments:
#      - ~
#      - AppBundle\Entity\TeamMember
#      - ~
#    calls:
#      - [ setTranslationDomain, [AppBundle] ]
#
#  rtf_block_admin:
#    class: AppBundle\Admin\RTFBlockAdmin
#    tags:
#      - { name: sonata.admin, manager_type: orm, group: 'group.rtf_block', label: 'group.rtf_block.rtf_block_editor' }
#    arguments:
#      - ~
#      - AppBundle\Entity\RTFBlock
#      - ~
#    calls:
#      - [ setTranslationDomain, [AppBundle] ]
#
#  html_page_admin:
#    class: AppBundle\Admin\HtmlPageAdmin
#    tags:
#      - { name: sonata.admin, manager_type: orm, group: 'group.html_page', label: 'group.html_page.html_page_editor' }
#    arguments:
#      - ~
#      - AppBundle\Entity\HtmlPage
#      - ~
#    calls:
#      - [ setTranslationDomain, [AppBundle] ]
