# Main page ============================================
index:
  path: /
  defaults:
    _controller: AppBundle:Default:index

top_100:
  path: /top-100
  defaults:
    _controller: AppBundle:Default:topBooks

#search:
#  path: /search.html
#  defaults:
#    _controller: AppBundle:Default:search
#
#rules:
#  path: /rules.html
#  defaults:
#    _controller: AppBundle:Default:rules
#
#rules_comments:
#  path: /rules-comments.html
#  defaults:
#    _controller: AppBundle:Default:rulesComments
#
#privacy:
#  path: /privacy-policy.html
#  defaults:
#    _controller: AppBundle:Default:privacy
#
#feedback:
#  path: /feedback.html
#  defaults:
#    _controller: AppBundle:Default:feedback
#
#orphus:
#  path: /orphus.html
#  defaults:
#    _controller: AppBundle:Default:orphus
#
#makehome:
#  path: /makehome/inctruktsija.html
#  defaults:
#    _controller: AppBundle:Default:makeHome
#
#block__ajax:
#  path: /_block/ajax/{blockType}/{blockId}
#  defaults:
#    _controller: AppBundle:Block:ajax
#  methods: [GET, POST]
#  requirements:
#    blockType: .+
#    blockId: .+