# Main page ============================================
index:
  path: /
  defaults:
    _controller: AppBundle:Default:index

#tv:
#  path: /tv.html
#  defaults:
#    _controller: AppBundle:Default:tv
#
#search:
#  path: /search.html
#  defaults:
#    _controller: AppBundle:Default:search
#
contacts:
  path: /contacts
  defaults:
    _controller: AppBundle:Default:contacts

#rules:
#  path: /rules.html
#  defaults:
#    _controller: AppBundle:Default:rules
#
#rules_comments:
#  path: /rules-comments.html
#  defaults:
#    _controller: AppBundle:Default:rulesComments
#
#privacy:
#  path: /privacy-policy.html
#  defaults:
#    _controller: AppBundle:Default:privacy
#
#feedback:
#  path: /feedback.html
#  defaults:
#    _controller: AppBundle:Default:feedback
#
#orphus:
#  path: /orphus.html
#  defaults:
#    _controller: AppBundle:Default:orphus
#
#makehome:
#  path: /makehome/inctruktsija.html
#  defaults:
#    _controller: AppBundle:Default:makeHome
#
#block__ajax:
#  path: /_block/ajax/{blockType}/{blockId}
#  defaults:
#    _controller: AppBundle:Block:ajax
#  methods: [GET, POST]
#  requirements:
#    blockType: .+
#    blockId: .+