services:
    order.block.order_board_list:
        class: "OrderBundle\\Block\\ListOrderBoardBlockService"
        arguments:
          - order.block.order_board_list
          - '@templating'
          - '@?doctrine'
        tags:
          - { name: sonata.block }